### ISSUE TITLE
¿Abandonamos JSON?

### ISSUE THREAD

**Issue by inigoflores** [codeforspain/datos#25]
A lo mejor hay que plantearse abandonar los archivos `.json` en favor de `.csv`. 

Motivos:
- **Tamaño**: JSON multiplica por 5 el tamaño de CSV (lo que crea problemas con GitHub si se superan los 100 megas).
- **Simplicidad**: Los perfiles no técnicos van a preferir CSV en vez de JSON.
- **Facilidad de proceso**: Los CSV son más fáciles de procesar por herramientas como `csvkit`.
- **Son el estándar**: Casi todos los datasets que he visto están en CSV o GeoJSON. No se encuentra casi nada en JSON. CSV tiene hasta una [conferencia propia](http://csvconf.com/)!
- **Redundancia y ruido**: Los JSON no proporcionan más que información que ya existe en los CSV, y que se puede convertir a JSON mediante un simple comando (e.j. `csvjson data.csv > data.json`), al alcance de cualquier desarrollador. 
  
  El propio Data Package Viewer te permite convertir y descargar los datos en cualquiera de los formatos, aunque el recurso esté solo en uno.  Un ejemplo: [European NUTS boundaries as GeoJSON at 1:60m](http://data.okfn.org/data/core/geo-nuts-administrative-boundaries). El [recurso](https://github.com/datasets/geo-nuts-administrative-boundaries/tree/master/data) está únicamente en GeoJson, pero el visualizador incluye enlaces para descargar el CSV y JSON de una copia local (que me imagino estará previamente convertida y guardada en la cache).

¿Qué opináis?

**Comment by dansmachina** [comment]
Aprovecho para dejar por aquí un breve resumen de formatos: http://opendatahandbook.org/guide/en/appendices/file-formats/

En cuanto al CSV, me quedo con esta reflexión: "a single omission of a field may disturb the reading of all remaining data in the file without any real opportunity to rectify it, because it cannot be determined how the remaining data should be interpreted." Aunque pueda tener ventajas, se hace difícil de manejar en algunos casos, por no hablar de que perdemos la estructura jerárquica que podemos encontrar en formatos como JSON, XML o derivados y que, desde mi punto de vista, puede resultar util.

**Comment by fesja** [comment]
Ver https://github.com/codeforspain/datos/issues/26, propongo una pausa en estos debates
